name: Update publications
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  query_ads:
    runs-on: ubuntu-latest
    env: 
      ADS_TOKEN: ${{ secrets.ADS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Query ADS
      run: ./update_bib.py
    - name: switching from HTTPS to SSH
      run: git remote set-url --add origin ${{ secrets.SSH }}
    - name: configure git email
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: configure git username
      run: git config --global user.name "github-actions[bot]"
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: Commit changes if any and push
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          git commit -m "Auto updating publications.bib"
          git fetch origin master
          git push origin HEAD:master
        else
          echo "No changes to commit"
        fi
